/* Generated By:JavaCC: Do not edit this line. CPPParserConstants.java */

package truerefactor.parsers.cpp;

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CPPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCURLYBRACE = 16;
  /** RegularExpression Id. */
  int RCURLYBRACE = 17;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 18;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 19;
  /** RegularExpression Id. */
  int LPARENTHESIS = 20;
  /** RegularExpression Id. */
  int RPARENTHESIS = 21;
  /** RegularExpression Id. */
  int SCOPE = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int QUESTIONMARK = 26;
  /** RegularExpression Id. */
  int ELLIPSIS = 27;
  /** RegularExpression Id. */
  int ASSIGNEQUAL = 28;
  /** RegularExpression Id. */
  int TIMESEQUAL = 29;
  /** RegularExpression Id. */
  int DIVIDEEQUAL = 30;
  /** RegularExpression Id. */
  int MODEQUAL = 31;
  /** RegularExpression Id. */
  int PLUSEQUAL = 32;
  /** RegularExpression Id. */
  int MINUSEQUAL = 33;
  /** RegularExpression Id. */
  int SHIFTLEFTEQUAL = 34;
  /** RegularExpression Id. */
  int SHIFTRIGHTEQUAL = 35;
  /** RegularExpression Id. */
  int BITWISEANDEQUAL = 36;
  /** RegularExpression Id. */
  int BITWISEXOREQUAL = 37;
  /** RegularExpression Id. */
  int BITWISEOREQUAL = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int BITWISEOR = 41;
  /** RegularExpression Id. */
  int BITWISEXOR = 42;
  /** RegularExpression Id. */
  int AMPERSAND = 43;
  /** RegularExpression Id. */
  int EQUAL = 44;
  /** RegularExpression Id. */
  int NOTEQUAL = 45;
  /** RegularExpression Id. */
  int LESSTHAN = 46;
  /** RegularExpression Id. */
  int GREATERTHAN = 47;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 48;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 49;
  /** RegularExpression Id. */
  int SHIFTLEFT = 50;
  /** RegularExpression Id. */
  int SHIFTRIGHT = 51;
  /** RegularExpression Id. */
  int PLUS = 52;
  /** RegularExpression Id. */
  int MINUS = 53;
  /** RegularExpression Id. */
  int STAR = 54;
  /** RegularExpression Id. */
  int DIVIDE = 55;
  /** RegularExpression Id. */
  int MOD = 56;
  /** RegularExpression Id. */
  int PLUSPLUS = 57;
  /** RegularExpression Id. */
  int MINUSMINUS = 58;
  /** RegularExpression Id. */
  int TILDE = 59;
  /** RegularExpression Id. */
  int NOT = 60;
  /** RegularExpression Id. */
  int DOT = 61;
  /** RegularExpression Id. */
  int POINTERTO = 62;
  /** RegularExpression Id. */
  int DOTSTAR = 63;
  /** RegularExpression Id. */
  int ARROWSTAR = 64;
  /** RegularExpression Id. */
  int AUTO = 65;
  /** RegularExpression Id. */
  int BREAK = 66;
  /** RegularExpression Id. */
  int CASE = 67;
  /** RegularExpression Id. */
  int CATCH = 68;
  /** RegularExpression Id. */
  int CHAR = 69;
  /** RegularExpression Id. */
  int CONST = 70;
  /** RegularExpression Id. */
  int CONTINUE = 71;
  /** RegularExpression Id. */
  int _DEFAULT = 72;
  /** RegularExpression Id. */
  int DELETE = 73;
  /** RegularExpression Id. */
  int DO = 74;
  /** RegularExpression Id. */
  int DOUBLE = 75;
  /** RegularExpression Id. */
  int ELSE = 76;
  /** RegularExpression Id. */
  int ENUM = 77;
  /** RegularExpression Id. */
  int EXTERN = 78;
  /** RegularExpression Id. */
  int FLOAT = 79;
  /** RegularExpression Id. */
  int FOR = 80;
  /** RegularExpression Id. */
  int FRIEND = 81;
  /** RegularExpression Id. */
  int GOTO = 82;
  /** RegularExpression Id. */
  int IF = 83;
  /** RegularExpression Id. */
  int INLINE = 84;
  /** RegularExpression Id. */
  int INT = 85;
  /** RegularExpression Id. */
  int LONG = 86;
  /** RegularExpression Id. */
  int NEW = 87;
  /** RegularExpression Id. */
  int PRIVATE = 88;
  /** RegularExpression Id. */
  int PROTECTED = 89;
  /** RegularExpression Id. */
  int PUBLIC = 90;
  /** RegularExpression Id. */
  int REDECLARED = 91;
  /** RegularExpression Id. */
  int REGISTER = 92;
  /** RegularExpression Id. */
  int RETURN = 93;
  /** RegularExpression Id. */
  int SHORT = 94;
  /** RegularExpression Id. */
  int SIGNED = 95;
  /** RegularExpression Id. */
  int SIZEOF = 96;
  /** RegularExpression Id. */
  int STATIC = 97;
  /** RegularExpression Id. */
  int STRUCT = 98;
  /** RegularExpression Id. */
  int CLASS = 99;
  /** RegularExpression Id. */
  int SWITCH = 100;
  /** RegularExpression Id. */
  int TEMPLATE = 101;
  /** RegularExpression Id. */
  int THIS = 102;
  /** RegularExpression Id. */
  int TRY = 103;
  /** RegularExpression Id. */
  int TYPEDEF = 104;
  /** RegularExpression Id. */
  int UNION = 105;
  /** RegularExpression Id. */
  int UNSIGNED = 106;
  /** RegularExpression Id. */
  int VIRTUAL = 107;
  /** RegularExpression Id. */
  int VOID = 108;
  /** RegularExpression Id. */
  int VOLATILE = 109;
  /** RegularExpression Id. */
  int WHILE = 110;
  /** RegularExpression Id. */
  int OPERATOR = 111;
  /** RegularExpression Id. */
  int TRUETOK = 112;
  /** RegularExpression Id. */
  int FALSETOK = 113;
  /** RegularExpression Id. */
  int THROW = 114;
  /** RegularExpression Id. */
  int OCTALINT = 115;
  /** RegularExpression Id. */
  int OCTALLONG = 116;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALINT = 117;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALLONG = 118;
  /** RegularExpression Id. */
  int DECIMALINT = 119;
  /** RegularExpression Id. */
  int DECIMALLONG = 120;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALINT = 121;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALLONG = 122;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 123;
  /** RegularExpression Id. */
  int HEXADECIMALLONG = 124;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALINT = 125;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALLONG = 126;
  /** RegularExpression Id. */
  int FLOATONE = 127;
  /** RegularExpression Id. */
  int FLOATTWO = 128;
  /** RegularExpression Id. */
  int CHARACTER = 129;
  /** RegularExpression Id. */
  int STRING = 130;
  /** RegularExpression Id. */
  int ID = 132;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 15>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"throw\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "\"finally\"",
    "<ID>",
  };

}
